### ISSUE TITLE
More Information about activities individual sessions (or even takes)

### ISSUE THREAD

**Issue by cschell** [facebookresearch/TalkingWithHands32M#5]
I'm interested in the types of activities each subject is doing, so I am already very happy about the `configs/conversations.json`. However, the conversations-sessions seem to start with session 14, so I'm wondering what the first 13 Sessions are about - it would be great to have more information about that.

Ideally that would be another json-file which contains some kind of label for each session (like "conversation", "motion tests", etc.), but I understand that that would take some effort. For me, however, it would already be very helpful to simply have some more information (in the Readme, for example) about what you did in the sessions (maybe like "in Session 1-5 we've tested the system, in Session 6-9 we've experimented with different scenarios"). I think that would add even more value to the dataset!

**Comment by shugaoma** [comment]
Hi @cschell, all sessions contain conversations. Basically for each session, we first capture some body gestures, and then several sessions of conversations. Please refer to our paper for more details.

**Comment by cschell** [comment]
Thanks for clearifying! Does this mean that `configs/conversations.json` is currently incomplete? 

To elaborate, in your Readme you state:

> Conversation takes
> 
> The dataset includes motion capture takes other than conversations, such as range of motion. We plan to provide additional information in the near future.
> 
> If you would like to use just the conversation takes, see configs/conversations.json to find out which takes are the conversation takes, and their corresponding lengths.

For my research I would like to make sure I have a rough understanding about the kind of activity subjects are engaged in, so my initial plan was to only include takes listed in your `configs/conversations.json`. However, I then noticed that that would exclude 1) about half of all sessions and 2) all sessions/takes with subjects "deep2" and "deep3". This brought me to the conclusion that all the sessions and takes _not_ mentioned in `configs/conversations.json` must have recordings of other activities than "conversations".

So I'm just wondering what a good strategy might be for me, if I wanted to exclude non-conversational takes without visually inspecting them first (which would be my last option, but first I would like to make sure I'm not missing something).

I also made sure to carefully re-read your paper, so if I'm ignorant of something you wrote there, please let me know!

**Comment by gilwoolee** [comment]
Hi @cschell , 

Thank you for your interest in our dataset. 

All sessions listed here contain conversation takes as well as other movements.

We are currently annotating the first batch of the sessions -- mainly to remove any personal information before releasing the audio dataset. As we do so, we plan to add them to the `conversations.json` file as well.

If you were to visually inspect the first batch of sessions, you will be able to find which ones are conversational ones. If I were to filter out just based on their high-level information, takes that have both participants (two `bvh` files) and are longer than 5 minutes are likely to be conversation sessions.

Of course, not that you should do this visual inspection; I would love to be able to provide more details on those sessions as soon as possible. Our team is going through them, but we do not have a set release date.

Hope this helps!

**Comment by cschell** [comment]
>  If I were to filter out just based on their high-level information, takes that have both participants (two bvh files) and are longer than 5 minutes are likely to be conversation sessions

That's a good tip, thank you!
